git:
  depth: 5

stages:
  - "Build and Test"
  - "Package"

jobs:
  include:
  - stage: "Build and Test"
    language: java
    jdk: oraclejdk11
    before_script:
    - cd sample-application-backend
    script:
    - mvn clean verify
  - stage: "Build and Test"
    language: node_js
    node_js: "12.20"
    before_script:
    - cd sample-application-frontend
  - stage: "Package"
    before_script:
    - cd sample-application-backend
    script:
    - docker build -t niakulu/devops:backend .
    - docker login -p $DOCKER_PASS -u $DOCKER_USER
    - docker push niakulu/devops:backend
  - stage: "Package"
    before_script:
    - cd sample-application-frontend
    script:
    - docker build -t niakulu/devops:frontend .
    - docker login -p $DOCKER_PASS -u $DOCKER_USER
    - docker push niakulu/devops:frontend

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.npm"

services:
- docker